### ISSUE TITLE
Date picker in "New Pad" Modal Screen not working

### ISSUE THREAD

**Issue by Lithimlin** [HackHerz/padwoman#1]
The date picker seen during the creation does not seem to work.
When clicking on "+ New Pad" and then on the calendar icon, nothing happens.
The date picker only opens when clicking on the date itself.

**Comment by HackHerz** [comment]
There is no calendar icon in the new pad modal. Also there is no date picker in the whole web ui. Could you provide a screenshot of what you mean?
