### ISSUE TITLE
Feature Request: Login for direct pad links

### ISSUE THREAD

**Issue by Peyje** [HackHerz/padwoman#4]
**Please Describe The Problem To Be Solved:** Padwomen currently does not provide an easy login if a link to a corresponding pad is followed but the user is not logged in. Instead, only the following message can be read:

> You do not have permission to access this pad

**(Optional): Suggest A Solution:** This could be solved by either redirecting the potential user to the login screen or by adding the login functionality to the "access denied" page.

**Comment by HackHerz** [comment]
This is not part of Padwoman and needs to be configured in etherpad.
